"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const VariableDiscount_1 = require("./modules/VariableDiscount");
const FixedDiscount_1 = require("./modules/FixedDiscount");
const NoDiscount_1 = require("./modules/NoDiscount");
const Product_1 = require("./modules/Product");
const ShoppingBasket_1 = require("./modules/ShoppingBasket");
let cart = new ShoppingBasket_1.ShoppingBasket();
cart.addProduct(new Product_1.Product('Chair', 25, new FixedDiscount_1.FixedDiscount(10)));
//cart.addProduct(new Product('Chair', 25, new Discount("fixed", -10)));
cart.addProduct(new Product_1.Product('Table', 50, new VariableDiscount_1.VariableDiscount(25)));
cart.addProduct(new Product_1.Product('Bed', 100, new NoDiscount_1.NoDiscount()));
const tableElement = document.querySelector('#cart tbody');
cart.products.forEach((product) => {
    let tr = document.createElement('tr');
    let td = document.createElement('td');
    td.innerText = product.name;
    tr.appendChild(td);
    td = document.createElement('td');
    td.innerText = product.originalPrice.toFixed(2) + ' €';
    tr.appendChild(td);
    td = document.createElement('td');
    td.innerText = product.calculatePrice().toFixed(2) + ' €';
    tr.appendChild(td);
    td = document.createElement('td');
    td.innerText = product.showCalculation();
    tr.appendChild(td);
    tableElement.appendChild(tr);
});
